/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;

/**
 *
 * @author f2018266389
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Costumer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addrecord = new javax.swing.JButton();
        seerecord = new javax.swing.JButton();
        back = new javax.swing.JButton();
        delrecord = new javax.swing.JButton();
        Solditem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Customers");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(262, 21, 129, 29);

        addrecord.setBackground(new java.awt.Color(0, 0, 0));
        addrecord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addrecord.setForeground(new java.awt.Color(255, 255, 255));
        addrecord.setText("Add Record");
        addrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrecordActionPerformed(evt);
            }
        });
        getContentPane().add(addrecord);
        addrecord.setBounds(70, 110, 242, 49);

        seerecord.setBackground(new java.awt.Color(0, 0, 0));
        seerecord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seerecord.setForeground(new java.awt.Color(255, 255, 255));
        seerecord.setText("See Record");
        seerecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seerecordActionPerformed(evt);
            }
        });
        getContentPane().add(seerecord);
        seerecord.setBounds(380, 260, 242, 49);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 364, 100, 50);

        delrecord.setBackground(new java.awt.Color(0, 0, 0));
        delrecord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delrecord.setForeground(new java.awt.Color(255, 255, 255));
        delrecord.setText("Delete Record");
        delrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delrecordActionPerformed(evt);
            }
        });
        getContentPane().add(delrecord);
        delrecord.setBounds(70, 260, 240, 50);

        Solditem.setBackground(new java.awt.Color(0, 0, 0));
        Solditem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Solditem.setForeground(new java.awt.Color(255, 255, 255));
        Solditem.setText("Sold Product");
        Solditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolditemActionPerformed(evt);
            }
        });
        getContentPane().add(Solditem);
        Solditem.setBounds(380, 110, 240, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/installmentcenter/Project Pics/multilingual_customer_support_WIDE.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 680, 420);

        setSize(new java.awt.Dimension(696, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrecordActionPerformed
       dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addcustomers().setVisible(true);
            }
        });
    }//GEN-LAST:event_addrecordActionPerformed

    private void seerecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seerecordActionPerformed
               dispose(); 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRecord().setVisible(true);
            }
        });  
       
    }//GEN-LAST:event_seerecordActionPerformed
        
                
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
               dispose(); 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });        // TODO add your handling code
    }//GEN-LAST:event_backActionPerformed

    private void SolditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolditemActionPerformed
          dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoldProduct().setVisible(true);
            }
        });
// TODO add your handling code here:
    }//GEN-LAST:event_SolditemActionPerformed

    private void delrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delrecordActionPerformed
         dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelCustomer().setVisible(true);
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_delrecordActionPerformed

            
                
    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Solditem;
    private javax.swing.JButton addrecord;
    private javax.swing.JButton back;
    private javax.swing.JButton delrecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton seerecord;
    // End of variables declaration//GEN-END:variables
}
